const COMPANY = "Multicorp Fire Protection Services";
const ADDRESS = "9693 Gerwig Lane, Columbia MD 21046";
const PHONE = "(410) 876-5000";

function triggerDownload(html: string, filename: string) {
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadDocument(
  fileName: string,
  opts?: { title?: string; subtitle?: string; date?: string; issuedBy?: string }
) {
  const title = opts?.title ?? fileName.replace(/\.\w+$/, "");
  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${title}</title>
<style>
  body{font-family:Arial,sans-serif;color:#1a1a1a;max-width:720px;margin:40px auto;padding:0 28px}
  .header{border-bottom:3px solid #8B1A1A;padding-bottom:18px;margin-bottom:28px;display:flex;justify-content:space-between;align-items:flex-start}
  h1{color:#8B1A1A;margin:0 0 5px;font-size:22px}
  h2{margin:0 0 18px;font-size:19px}
  .meta{color:#555;font-size:13px;margin:3px 0}
  .badge{display:inline-block;background:#16a34a;color:#fff;padding:5px 14px;border-radius:20px;font-size:13px;font-weight:600;margin-top:18px}
  .body-block{background:#f9f9f9;border:1px solid #eee;border-radius:8px;padding:20px 24px;margin-top:20px;line-height:1.7}
  .footer{margin-top:48px;padding-top:14px;border-top:1px solid #ddd;color:#aaa;font-size:11px;text-align:center}
</style></head>
<body>
<div class="header">
  <div><h1>${COMPANY}</h1><p class="meta">${ADDRESS}</p><p class="meta">${PHONE}</p></div>
  <div style="text-align:right;margin-top:4px"><p class="meta" style="font-size:12px">TechForce Pro</p></div>
</div>
<h2>${title}</h2>
${opts?.subtitle ? `<p class="meta"><strong>${opts.subtitle}</strong></p>` : ""}
${opts?.date ? `<p class="meta">Date: ${opts.date}</p>` : ""}
${opts?.issuedBy ? `<p class="meta">Issued by: ${opts.issuedBy}</p>` : ""}
<span class="badge">&#10003; Official Document</span>
<div class="body-block">
  <p>This document was issued by ${COMPANY} and is certified accurate at the time of issuance.</p>
  <p>File reference: <strong>${fileName}</strong></p>
</div>
<div class="footer">Generated by TechForce Pro &middot; ${COMPANY} &middot; ${PHONE}</div>
</body></html>`;
  triggerDownload(html, fileName.replace(/\.(pdf|docx?)$/i, ".html") || fileName + ".html");
}

export interface EstimateForDownload {
  estimateNumber: string;
  customerName: string;
  contactName?: string | null;
  techName?: string | null;
  created: string;
  validUntil: string;
  lineItems: { service: string; description?: string; qty: number; unitPrice: number }[];
  notes?: string;
  taxPct: number;
  status: string;
}

export function downloadEstimatePdf(est: EstimateForDownload) {
  const fmt = (v: number) => `$${v.toFixed(2)}`;
  const sub  = est.lineItems.reduce((s, l) => s + l.qty * l.unitPrice, 0);
  const tax  = sub * (est.taxPct / 100);
  const total = sub + tax;
  const fmtDate = (d: string) => {
    const dt = new Date(d + "T12:00:00");
    return dt.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
  };

  const rows = est.lineItems.map(l => `
    <tr>
      <td style="padding:10px 14px;border-bottom:1px solid #f0f0f0">${l.service}</td>
      <td style="padding:10px 14px;border-bottom:1px solid #f0f0f0;color:#666;font-size:12px">${l.description ?? ""}</td>
      <td style="padding:10px 14px;border-bottom:1px solid #f0f0f0;text-align:center">${l.qty}</td>
      <td style="padding:10px 14px;border-bottom:1px solid #f0f0f0;text-align:right">${fmt(l.unitPrice)}</td>
      <td style="padding:10px 14px;border-bottom:1px solid #f0f0f0;text-align:right;font-weight:600">${fmt(l.qty * l.unitPrice)}</td>
    </tr>`).join("");

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Estimate ${est.estimateNumber}</title>
<style>
  body{font-family:Arial,sans-serif;color:#1a1a1a;max-width:780px;margin:40px auto;padding:0 28px}
  .header{border-bottom:3px solid #8B1A1A;padding-bottom:18px;margin-bottom:28px;display:flex;justify-content:space-between;align-items:flex-end}
  h1{color:#8B1A1A;margin:0 0 4px;font-size:21px}
  .meta{color:#555;font-size:13px;margin:3px 0}
  .est-num{font-size:22px;font-weight:700;color:#333}
  .status-badge{display:inline-block;padding:3px 12px;border-radius:12px;font-size:12px;font-weight:700;background:#f3e8ff;color:#6b21a8;text-transform:uppercase}
  .bill-grid{display:grid;grid-template-columns:1fr 1fr 1fr;gap:20px;margin-bottom:24px}
  .bill-label{font-size:11px;font-weight:700;color:#888;text-transform:uppercase;margin-bottom:4px}
  .bill-value{font-size:14px;font-weight:600}
  table{width:100%;border-collapse:collapse;margin-top:4px}
  th{background:#f8f8f8;padding:10px 14px;text-align:left;font-size:12px;color:#555;border-bottom:2px solid #eee}
  .total-row td{font-weight:700;font-size:17px;color:#8B1A1A;border-top:2px solid #eee;padding:14px}
  .notes-box{margin-top:20px;padding:14px 18px;background:#fafafa;border:1px solid #eee;border-radius:8px;font-size:13px;color:#444;line-height:1.6}
  .validity{margin-top:12px;padding:10px 16px;background:#fffbeb;border:1px solid #fde68a;border-radius:8px;font-size:12px;color:#92400e}
  .footer{margin-top:48px;padding-top:14px;border-top:1px solid #ddd;color:#aaa;font-size:11px;text-align:center}
</style></head>
<body>
<div class="header">
  <div><h1>${COMPANY}</h1><p class="meta">${ADDRESS}</p><p class="meta">${PHONE}</p></div>
  <div style="text-align:right">
    <div class="est-num">ESTIMATE&nbsp;${est.estimateNumber}</div>
    <p class="meta">Date Issued: ${fmtDate(est.created)}</p>
    <span class="status-badge">${est.status.toUpperCase()}</span>
  </div>
</div>
<div class="bill-grid">
  <div><div class="bill-label">Prepared For</div><div class="bill-value">${est.customerName}</div>${est.contactName ? `<div class="meta">${est.contactName}</div>` : ""}</div>
  <div><div class="bill-label">Prepared By</div><div class="bill-value">${est.techName ?? COMPANY}</div></div>
  <div><div class="bill-label">Valid Until</div><div class="bill-value">${fmtDate(est.validUntil)}</div></div>
</div>
<table>
  <thead><tr>
    <th>Service</th><th>Description</th>
    <th style="text-align:center">Qty</th>
    <th style="text-align:right">Unit Price</th>
    <th style="text-align:right">Total</th>
  </tr></thead>
  <tbody>${rows}</tbody>
  <tfoot>
    <tr><td colspan="4" style="text-align:right;padding:10px 14px;color:#666;font-size:13px">Subtotal</td><td style="text-align:right;padding:10px 14px;font-size:13px">${fmt(sub)}</td></tr>
    ${est.taxPct > 0 ? `<tr><td colspan="4" style="text-align:right;padding:6px 14px;color:#666;font-size:13px">Tax (${est.taxPct}%)</td><td style="text-align:right;padding:6px 14px;font-size:13px">${fmt(tax)}</td></tr>` : ""}
    <tr class="total-row"><td colspan="4" style="text-align:right">TOTAL ESTIMATE</td><td style="text-align:right">${fmt(total)}</td></tr>
  </tfoot>
</table>
${est.notes ? `<div class="notes-box"><strong>Notes / Terms:</strong><br>${est.notes}</div>` : ""}
<div class="validity">&#9432; This estimate is valid until <strong>${fmtDate(est.validUntil)}</strong>. Prices are subject to change after this date.</div>
<div class="footer">TechForce Pro &middot; ${COMPANY} &middot; ${PHONE} &middot; This is an estimate, not an invoice.</div>
</body></html>`;
  triggerDownload(html, `${est.estimateNumber}.html`);
}

export interface InvoiceForDownload {
  invoiceNumber: string;
  customerName: string;
  techName?: string | null;
  status: string;
  totalAmount: string | number;
  generatedAt?: string | null;
  lineItems: { service: string; quantity: number; rate: number | string; total: number | string }[];
}

export function downloadInvoicePdf(inv: InvoiceForDownload) {
  const fmt = (v: string | number) => `$${Number(v).toFixed(2)}`;
  const dateStr = inv.generatedAt
    ? new Date(inv.generatedAt).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })
    : new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });

  const rows = inv.lineItems
    .map(
      l => `<tr>
      <td style="padding:10px 14px;border-bottom:1px solid #f0f0f0">${l.service}</td>
      <td style="padding:10px 14px;border-bottom:1px solid #f0f0f0;text-align:center">${l.quantity}</td>
      <td style="padding:10px 14px;border-bottom:1px solid #f0f0f0;text-align:right">${fmt(l.rate)}</td>
      <td style="padding:10px 14px;border-bottom:1px solid #f0f0f0;text-align:right;font-weight:600">${fmt(l.total)}</td>
    </tr>`
    )
    .join("");

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Invoice ${inv.invoiceNumber}</title>
<style>
  body{font-family:Arial,sans-serif;color:#1a1a1a;max-width:760px;margin:40px auto;padding:0 28px}
  .header{border-bottom:3px solid #8B1A1A;padding-bottom:18px;margin-bottom:28px;display:flex;justify-content:space-between;align-items:flex-end}
  h1{color:#8B1A1A;margin:0 0 4px;font-size:21px}
  .meta{color:#555;font-size:13px;margin:3px 0}
  .inv-num{font-size:22px;font-weight:700;color:#333}
  .status{display:inline-block;padding:3px 12px;border-radius:12px;font-size:12px;font-weight:700;background:#dcfce7;color:#166534;text-transform:uppercase}
  .bill-grid{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-bottom:24px}
  .bill-label{font-size:11px;font-weight:700;color:#888;text-transform:uppercase;margin-bottom:4px}
  .bill-value{font-size:15px;font-weight:600}
  table{width:100%;border-collapse:collapse;margin-top:4px}
  th{background:#f8f8f8;padding:10px 14px;text-align:left;font-size:13px;color:#555;border-bottom:2px solid #eee}
  .total-row td{font-weight:700;font-size:17px;color:#8B1A1A;border-top:2px solid #eee;padding:14px}
  .footer{margin-top:48px;padding-top:14px;border-top:1px solid #ddd;color:#aaa;font-size:11px;text-align:center}
</style></head>
<body>
<div class="header">
  <div><h1>${COMPANY}</h1><p class="meta">${ADDRESS}</p><p class="meta">${PHONE}</p></div>
  <div style="text-align:right">
    <div class="inv-num">${inv.invoiceNumber}</div>
    <p class="meta">Date: ${dateStr}</p>
    <span class="status">${inv.status}</span>
  </div>
</div>
<div class="bill-grid">
  <div><div class="bill-label">Bill To</div><div class="bill-value">${inv.customerName}</div></div>
  <div><div class="bill-label">Technician</div><div class="bill-value">${inv.techName ?? "Unassigned"}</div></div>
</div>
<table>
  <thead><tr>
    <th>Service Description</th>
    <th style="text-align:center">Qty</th>
    <th style="text-align:right">Unit Rate</th>
    <th style="text-align:right">Total</th>
  </tr></thead>
  <tbody>${rows}</tbody>
  <tfoot><tr class="total-row">
    <td colspan="3" style="text-align:right">TOTAL DUE</td>
    <td style="text-align:right">${fmt(inv.totalAmount)}</td>
  </tr></tfoot>
</table>
<div class="footer">Thank you for your business &middot; TechForce Pro &middot; ${COMPANY}</div>
</body></html>`;
  triggerDownload(html, `${inv.invoiceNumber}.html`);
}
